# Generated by Django 5.1.7 on 2025-03-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.URLField()),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
